### ISSUE TITLE
Unable to load shared library 'kernel32.dll' on macOS

### ISSUE THREAD

**Issue by helgeblod** [man-group/dapr-sidekick-dotnet#11]
## Expected Behavior

Starting more than a single dapr-service via dapr-sidekick should be possible on macOS

## Actual Behavior

Starting a single service seems to work, starting a second one results in this error message: 

```
System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32.dll, 1): image not found
   at Man.Dapr.Sidekick.Native.NativeProcess.OpenProcess(OpenProcessDesiredAccessFlags dwDesiredAccess, Boolean bInheritHandle, UInt32 dwProcessId)
   at Man.Dapr.Sidekick.Native.NativeProcess.GetCommandLine(Process process, String& commandLine)
   at Man.Dapr.Sidekick.Process.ProcessCommandLine..ctor(SystemProcess systemProcess)
   at Man.Dapr.Sidekick.Process.SystemProcess.GetCommandLine()
   at Man.Dapr.Sidekick.Process.DaprProcess`1.CheckExistingProcesses(TOptions proposedOptions)
   at Man.Dapr.Sidekick.Process.DaprProcess`1.Initialize(DaprCancellationToken cancellationToken)
```

## Steps to Reproduce the Problem

On MacOS (Big Sur), start two services via `dotnet run` at the same time (both using `services.AddDaprSidekick` as a configured service). Last service to start will result in above error. Also, the error appears when running the tests in the `dapr-sidekick-dotnet`-project on macOS:

```
Man.Dapr.Sidekick.Process.ProcessCommandLineTests+Constructor.Should_retrieve_commandline

System.EntryPointNotFoundException : OpenProcess assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Man.Dapr.Sidekick.Native.NativeProcess.OpenProcess(Man.Dapr.Sidekick.Native.NativeProcess/OpenProcessDesiredAccessFlags,bool,uint)
  at Man.Dapr.Sidekick.Native.NativeProcess.GetCommandLine (System.Diagnostics.Process process, System.String& commandLine) [0x00006] in /dapr-sidekick-dotnet/src/Man.Dapr.Sidekick/Native/NativeProcess.cs:89 
  at Man.Dapr.Sidekick.Process.ProcessCommandLine..ctor (Man.Dapr.Sidekick.Process.SystemProcess systemProcess) [0x00000] in /dapr-sidekick-dotnet/src/Man.Dapr.Sidekick/Process/ProcessCommandLine.cs:10 
  at Man.Dapr.Sidekick.Process.ProcessCommandLineTests+Constructor.Should_retrieve_commandline () [0x0000e] in /dapr-sidekick-dotnet/tests/Man.Dapr.Sidekick.Tests/Process/ProcessCommandLineTests.cs:14 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
```
## Release Note

RELEASE NOTE: 

*Note:* I started digging around in the code and it occurred to me that this might actually be the expected behaviour. The problematic code is in `NativeProcess.cs` and the second line of that file (https://github.com/man-group/dapr-sidekick-dotnet/blob/main/src/Man.Dapr.Sidekick/Native/NativeProcess.cs#L2) mentions a StackOverflow article. I had a look and the NativeProcess.cs implementation is inspired by this project: https://github.com/sonicmouse/ProcCmdLine. In the [README](https://github.com/sonicmouse/ProcCmdLine/blob/master/README.md) of mentioned project, it is said that this implementation is Windows only. It would be great if you would consider Mac/Linux support as Dapr Sidekick is a sorely missed feature that addresses an issue we have had in our team for a long time ❤️

**Comment by badgeratu** [comment]
First, great to hear that it generally works on MacOS - it's not a scenario we've had a chance to try yet. The issue you're seeing is in the area where Sidekick detects an existing running `daprd` process and tries to obtain the command-line parameters to see if it was launched with the same AppId and Port as the hosting service. If they match then it attempts to "attach" to that instance rather than launching a new one as you cannot have multiple `daprd` instances on the same computer with the same AppId. However .NET does not include a cross-platform way of obtaining these process arguments so we had to use a native Windows-only approach.

As this "attach" feature can't currently work on non-Windows platforms anyway (at least until a Linux/Mac developer contributes a change to support it) I suggest we just skip over the check for those platforms and try to start the second Dapr instance. Worst case Dapr will fail to start if it's using the same AppId as an existing running process, but for those like yourself that don't need the "attach" feature anyway it would at least solve this issue.

Does that sound reasonable?

**Comment by helgeblod** [comment]
Great, thanks! This sounds like a good solution! I'll test the fix and comment  I encounter any problems 👍
